name: MSBuild Build and Pack

on:
  push:
    branches:
    - main
    paths:
    - '**.csproj'
    - '**.nuspec'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Add GitHub Packages for Nuget
      run: |
        nuget sources add -Source https://nuget.pkg.github.com/bassclefstudio/index.json -Name "GPR" -Username bassclefstudio -Password ${{ secrets.GITHUB_TOKEN }} -StorePasswordInClearText
        dotnet nuget add source https://nuget.pkg.github.com/bassclefstudio/index.json --name "GPR" --username bassclefstudio --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: MSBuild
      run: msbuild BassClefStudio.AppModel.sln -t:build -p:Configuration=Debug -p:Platform="Any CPU" -m -restore
    - name: Nuget Pack
      run: |
        dotnet pack .\BassClefStudio.AppModel\BassClefStudio.AppModel.csproj --no-build
        nuget pack .\BassClefStudio.AppModel.Uwp\BassClefStudio.AppModel.Uwp.csproj
    - name: Nuget Push
      run: dotnet nuget push "**.nupkg" --source "GPR" --skip-duplicate --no-symbols true